### ISSUE TITLE
words that aren't appropriate for @godtributes, but don't belong in iscool?

### ISSUE THREAD

**Issue by fitnr** [jimkang/godtributes#38]
This tweet from seems, um, not cool: 
```
FASCISTS FOR THE FASCIST GOD! FUHRERS FOR THE FUHRER THRONE
```
(https://twitter.com/godtributes/status/798652572366041088)

But it doesn't necessarily seem appropriate to add the words in question to the iscool or wordfilter blacklists. Maybe they belong on a temporary blacklist?

**Comment by jimkang** [comment]
Oof. On one hand, some people interpret tributes as endorsements but others interpret them as sacrifices. On the other, everyone is sore right now and tends to pick the most depressing read, including me.

**Comment by jimkang** [comment]
OK, avoiding talking about fascism for now.
