### ISSUE TITLE
Tribby using words from blacklist?

### ISSUE THREAD

**Issue by vmbrasseur** [jimkang/godtributes#40]
See here:

https://twitter.com/godtributes/status/954390171532840960

The word 'abuser' is on the [extended blacklist](https://github.com/jimkang/iscool/blob/master/defaultlists.js#L83).

**Comment by jimkang** [comment]
Aw dang. It's actually responding to `abusers` in the retweet and singularizing it. I try to always put in the plural forms, but looks like I forgot.

**Comment by jimkang** [comment]
[Plural added.](https://github.com/jimkang/iscool/commit/22bd71dcc2e22dba8eba570d9483927d1987e940) It should not do this again.
